// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: verify_email.sql

package db

import (
	"context"
)

const createVerificationEmail = `-- name: CreateVerificationEmail :one
INSERT INTO verification_emails (
  username,
  email,
  secter_code
) VALUES (
  $1, $2, $3
) RETURNING id, username, email, secter_code, is_used, created_at, expired_at
`

type CreateVerificationEmailParams struct {
	Username   string `json:"username"`
	Email      string `json:"email"`
	SecterCode string `json:"secter_code"`
}

func (q *Queries) CreateVerificationEmail(ctx context.Context, arg CreateVerificationEmailParams) (VerificationEmail, error) {
	row := q.db.QueryRowContext(ctx, createVerificationEmail, arg.Username, arg.Email, arg.SecterCode)
	var i VerificationEmail
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.SecterCode,
		&i.IsUsed,
		&i.CreatedAt,
		&i.ExpiredAt,
	)
	return i, err
}
