# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: root 
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.4'

    - name: Install golang migrate
      run: |
       curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.3/migrate.linux-amd64.tar.gz | tar xvz
       sudo mv migrate /usr/bin
       which migrate

    - name: Run migrations
      run: make migratetestup

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_DB_DRIVER: postgres
        envkey_DB_SOURCE: postgresql://root:secret@localhost:5432/simple_bank_test?sslmode=disable
        envkey_DB_SOURCE_TEST: postgresql://root:secret@localhost:5432/simple_bank_test?sslmode=disable
        envkey_SERVER_ADDRESS: 0.0.0.0:8080
        envkey_TOKEN_SYMMETRIC_KEY: 12345678901234567890123456789012
        envkey_ACCESS_TOKEN_DURATION: 15m
        file_name: app.env

    - name: Test
      run: make test